// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDW02n15n3suBWuHHTyPhWzjJ4wgf_2xpU',
    appId: '1:851084454779:web:7d2f4634791beae98b2bde',
    messagingSenderId: '851084454779',
    projectId: 'gestiapbd',
    authDomain: 'gestiapbd.firebaseapp.com',
    storageBucket: 'gestiapbd.firebasestorage.app',
    measurementId: 'G-2G67K82EQQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACptSa1VgRAdAyVpiQNak_KGN-DfO7Amc',
    appId: '1:851084454779:android:73fa2a45052108fb8b2bde',
    messagingSenderId: '851084454779',
    projectId: 'gestiapbd',
    storageBucket: 'gestiapbd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD78Lx4RcRgzevl6EjazFCPXGV4EY1dLz8',
    appId: '1:851084454779:ios:bd215631afa6ec4c8b2bde',
    messagingSenderId: '851084454779',
    projectId: 'gestiapbd',
    storageBucket: 'gestiapbd.firebasestorage.app',
    iosBundleId: 'com.example.gestiap',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD78Lx4RcRgzevl6EjazFCPXGV4EY1dLz8',
    appId: '1:851084454779:ios:bd215631afa6ec4c8b2bde',
    messagingSenderId: '851084454779',
    projectId: 'gestiapbd',
    storageBucket: 'gestiapbd.firebasestorage.app',
    iosBundleId: 'com.example.gestiap',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDW02n15n3suBWuHHTyPhWzjJ4wgf_2xpU',
    appId: '1:851084454779:web:a19c6f2feed6bf108b2bde',
    messagingSenderId: '851084454779',
    projectId: 'gestiapbd',
    authDomain: 'gestiapbd.firebaseapp.com',
    storageBucket: 'gestiapbd.firebasestorage.app',
    measurementId: 'G-DCZQ5D8WPS',
  );
}
